### ISSUE TITLE
Game alias in game activity title

### ISSUE THREAD

**Issue by Flieh** [zond/android-diplicity#35]
Once I have more than a single game underway I find that I often have difficulty knowing which game I'm playing and who I am playing against. You gave us the possibility to assign aliases to games but I think the effect needs to be extend so that that is the name we see **inside** the game. Many people have created games with the initial name of 'test' or 'letsdothis' so that I have several games with the same name. I gave them all aliases to distinguish them but this is only useful from the game list screen. Often we enter the app directly into a game due to clicking on a notification and I have no idea what game this is (yeah I can see its 'test' but which one?). So could we have aliases that propagate through out the app...? 

But of course we still need to be able to refer to these games from outside the app (forums, hangouts, support tickets) and here the aliases and even the original names for that matter are of no use. We also need a **unique ID** like the Droidippy game number.

**Comment by zond** [comment]
Oh, I thought I fixed the alias to be visible inside the games. That's a bug.

The unique ID thing if a separate issue.

Please post one issue for each item :)
