### ISSUE TITLE
Player Roster from inside each game

### ISSUE THREAD

**Issue by Flieh** [zond/android-diplicity#36]
When I've got a few games underway, I can't always recall who I'm playing against. The game list screen gives me a list of the players, but it would be **really** useful to be able to retrieve this information from inside each game. Once I've created specific chat channels, I'm able to get info on my correspondents but the information is missing until I've actually sent some press. You have the Game Settings page configured to mute or unmute countries, would this not be an appropriate place to have everyone's icon linked to their profile (the way it is on open chat channels) ?

**Comment by zond** [comment]
Good idea! Please rename the issue so I understand it from the issue list :)

**Comment by zond** [comment]
So, the suggested solution is to list player icons on the game settings view

**Comment by BlueTeck** [comment]
Maybe this could be combined with #32

**Comment by zond** [comment]
Not a bad idea.
