### ISSUE TITLE
Unique ID redux

### ISSUE THREAD

**Issue by Flieh** [zond/android-diplicity#38]
You gave us a  unique ID in the game settings and this is a good first step. Wouldn't it also be useful to have a simple incrementing integer ID as well ? **Especially helpful** would be to have it on the game list screen. The long form unique is not very helpful when trying to tell somewhat what game I'm talking about, but  game 42337 is much more vivid.

**Comment by zond** [comment]
There is no incrementing ID in datastore unfortunately. We need some way to link to games...

**Comment by zond** [comment]
Maybe if the app registered itself as handler of a particular URL, say: https://android-diplicity/Game/{game_id}, and when opened for such a link displays a game list with only one game - the one in the URL.

SG?

**Comment by zond** [comment]
Now you can link to particular games. I believe this solves the underlying problem. Feel free to reopen if not.
