### ISSUE TITLE
Game list screen

### ISSUE THREAD

**Issue by Flieh** [zond/android-diplicity#39]
I think it would be extremely helpful to have at least two more pieces of info on the Game List. One is an immutable game number as I mentioned in issue 38. Another **very helpful** info would be to know if I'm currently considered nmr. Maybe just have this as an asterisk or exclamation point until I give a set of orders or tick the RDY box.

**Comment by zond** [comment]
It would be fairly easy to add that to the expanded view. Less easy to add it to the non-expanded view without killing performance.

Would having it on the expanded view be good enough?

**Comment by Flieh** [comment]
I have five games running, that's a lot for me but there are many players that often have many more at a time. When I open my started games list it would be hugely helpful to see at a glance which games need my attention. Droidippy does this by classing the games as 'waiting' and 'orders needed'. Maybe another way would be to color code the entries? I know I'm only seeing the design impact and not the performance implications. Expanded view would be second best.

**Comment by zond** [comment]
I have the icons for NMR/READY in a game, and I will consider that to be closing this issue.
