### ISSUE TITLE
Add button for phase change in the map

### ISSUE THREAD

**Issue by Flieh** [zond/android-diplicity#42]
The fact that you can swipe left and right to see the map in different phases is a nice feature but it's a bit difficult to know exactly where and how to swipe. Using **next** and **prev** buttons might make things a bit more intuitive.

**Comment by zond** [comment]
Yeah, I know.

I just can't bring myself to introduce more clutter - for those who are aware, the swiping is much superiour as a method since it doesn't take up screen real estate.

Someone might want to create a setting where the user selects whether they want back/forward buttons?

**Comment by zond** [comment]
Fixed
