### ISSUE TITLE
Variant information display

### ISSUE THREAD

**Issue by tttppp** [zond/android-diplicity#47]
New players are currently confused by variants, as they are expecting to play classical. We should do something so that it's obvious to new players if they're signing up to a "standard" game or not.

Perhaps games lists should be sorted by variant, and then by number of players? Or maybe a rule that puts Classical games first, then everything else second?

It should also definitely be possible to read a description of the variants, eg when creating a new game. It would be good to include a map of the starting position along with this information.

**Comment by tttppp** [comment]
Perhaps just the word Variant next to games which aren't Classical?

**Comment by zond** [comment]
I'm all for this - show me a PR :)

**Comment by tttppp** [comment]
Ok, as a first attempt I hope to update the app to show the word "Variant" before the name of it (unless it's case insensitivity equal to the word Classical).

**Comment by zond** [comment]
Sounds good

**Comment by tttppp** [comment]
I started adding in game help here:

https://github.com/zond/android-diplicity/tree/VariantInfoView

Initially the idea is to add a page with the information exposed by the API.

**Comment by zond** [comment]
Great!

**Comment by tttppp** [comment]
Everything in this ticket is now done, except for reading the description when creating a game. It's possible (although awkward) to read the description before joining the game though.  I'm going to close this now, but obviously anyone should feel free to improve it if they want to.

Hopefully we have now solved the problem of players being in a new variant and not knowing what to do.
