### ISSUE TITLE
Generated game names

### ISSUE THREAD

**Issue by tttppp** [zond/android-diplicity#48]
People are generally very bad at coming up with interesting, or worthwhile game names. Most names fall into a few categories:
 * Information duplicated by the listing page (e.g. the turn length, or variant name)
 * Random keyboard bashing or a random word
 * Nothing at all (the empty string)

IMO it would be nice to suggest a randomly generated title for the game, so that they are more easily found in a list of games and remembered.  I propose using the following structure:

The [synonym of battle] for the [adjective] [noun]

If people don't want to think of a name then this will make their game easily identifiable. If people want to change the game name then they're free to.

**Comment by zond** [comment]
Might even include adjectives based on the filters, so that games with minimum hated are distinguishable from games with minium reliability, for example.

**Comment by jphendrix** [comment]
I am not an android programmer but I could certainly write a function getRandomName() function in Java if someone else could do the implementation.  Maybe use an XML or JSON file for synonym, adjective, noun dictionary?  Or if it would be more helpful for me to just create the dictionary, I could do that too.

**Comment by zond** [comment]
First, is it the client or server that should set up generated names? If the client - sure, let the Android app pre-generate a game name :)

A PR would be great!

**Comment by jphendrix** [comment]
I say do it in the client since it is really the user's responsibility to create the name anyway.  Plus it would be easy to let the user customize/localize later.

**Comment by zond** [comment]
Sounds good to me

**Comment by jphendrix** [comment]
OK.  I will work on a dictionary first.

**Comment by tttppp** [comment]
I made a start on this using the suggestion from Zond above about taking the game parameters as inputs. I thought the battle synonym could be from a list determined by the phase duration (e.g. a strike is short, a war is long). The remaining parameters could determine the list to pick the adjective from, and I was planning on the noun being completely random each time.

I also thought the words should come from localised resource files, as it seemed useful for users to advertise what language they wanted to have discussions in. Presumably all discussions are English at the moment? At least no one has tried to arrange an alliance with me in another language yet!

**Comment by zond** [comment]
Sounds awesome!
