### ISSUE TITLE
SVG Map doesn't fill width of screen

### ISSUE THREAD

**Issue by tttppp** [zond/android-diplicity#50]
For example when you open a Pure game you get a black margin down the right, even if there's enough vertical space to enlarge the map. It would be good if maps filled more of the screen by default.

**Comment by zond** [comment]
I agree - tried to make it work better when I created the map view but failed :/

**Comment by tttppp** [comment]
If it's difficult then the easy fix is to change all the maps to say they're the same size! The last time I tried deploying the app with Android Studio, I had problems with some of the screens (there was some complaint about missing resources). Maybe I'll be more lucky next time.

**Comment by zond** [comment]
Patches are welcome as always :)

**Comment by tttppp** [comment]
This has now been done here: https://github.com/zond/godip/commit/57d14c148c686e82edcb8019b796fd37f68e1684

I remember there being an issue with this fix in the past, but I tested this with two devices and both worked fine, so I've pushed it live.  I also need to update the SVGVersion for each variant - I'll do that now.

If we get complaints then these are the changes that need reverting! :-)
