### ISSUE TITLE
Ready button on map screen

### ISSUE THREAD

**Issue by tttppp** [zond/android-diplicity#51]
As suggested in the forum, it would be good to be able to submit orders by clicking a ready button on the map screen (rather than navigating to the phase settings).

This might have the side effect that more users would click ready and so more games might move faster.

https://groups.google.com/forum/m/#!topic/diplicity-talk/fkMudAqlz58

**Comment by zond** [comment]
Great idea!

**Comment by GijsTimmers** [comment]
I think this issue can be closed now.

**Comment by GijsTimmers** [comment]
:+1:

**Comment by zond** [comment]
Ah, true. Thanks :)
