### ISSUE TITLE
Map's zoom buttons overlap the next phase button

### ISSUE THREAD

**Issue by GijsTimmers** [zond/android-diplicity#58]

**Comment by zond** [comment]
Gah, annoying - the map zoom buttons are added by the web view and not
positioned by the app. Where should we put the phase buttons instead?

**Comment by tttppp** [comment]
On my phone the map buttons take up half the width of the screen, so the only real option I can think of is to reduce the height of the web view slightly.

**Comment by zond** [comment]
Could move the phase change buttons to the top of the screen?

**Comment by GijsTimmers** [comment]
I don't think there's many users who can't use pinch zoom nowadays, so you could consider disabling the buttons: https://stackoverflow.com/questions/10766669/how-to-remove-zoom-buttons-on-android-webview#10766678

**Comment by zond** [comment]
It's true, they might be redundant.


But I kind of liked outsourcing them completely to the web view renderer,
and letting the developers of the web view decide :)

**Comment by flurbius** [comment]
Eventually, put a checkbox in the app settings page, for now just turn them off by default.

As a work around if you don't touch the map for a few seconds they go away.

**Comment by flurbius** [comment]
OK I propose to squash this by the following method

phase 1:
    Remove the map controls
phase 2:
    Re-organise settings (i will find the issue and update this with a link) insert a checkbox to allow the user to bring back the map zoom controls.

Any objections?

**Comment by GijsTimmers** [comment]
SGTM

**Comment by zond** [comment]
Fixed in https://github.com/zond/android-diplicity/commit/e5bb4dea10faf10e3992808c611384f299708e94
