### ISSUE TITLE
Please release debug apks for testers

### ISSUE THREAD

**Issue by GijsTimmers** [zond/android-diplicity#64]
It would be nice if we can accompany the bug reports with logcats.

**Comment by zond** [comment]
How does that work? Can the app access logs for debug APKs, but not regular
ones?

**Comment by GijsTimmers** [comment]
I'm not sure but I believe that apks are "stripped" from output when
uploading them to Google Play, and can't be logcatted anymore.

**Comment by GijsTimmers** [comment]
Invalid. Logcat works on apks released from the app store.

**Comment by zond** [comment]
Ok, closing then :)
