### ISSUE TITLE
"Toscana" should be Tuscany

### ISSUE THREAD

**Issue by Enriador** [zond/android-diplicity#67]
The province is written in Italian for some reason.

**Comment by tttppp** [comment]
I'm happy to fox and deploy this if @zond agrees it's not meant to be like that. I'm loath to change it without approval, because I originally thought that Rumania was spelt incorrectly, but it turns out to be accurate for the time period.

**Comment by Enriador** [comment]
I am sure @zond will agree.

Rumania is historically accurate, AND was always called this in Diplomacy maps ever since launch in 1958. Tuscany was called that in the early 20th century English-speaking world, AND is how it has always been written down in Dip boards.

Thanks for the quick answer!

**Comment by zond** [comment]
I originally used "native names from the period" on the map, but someone
(Chris Babcock?) changed the names to "standard dippy names" instead.

And that's currently the stated policy for province naming. So, if there is
a more "standard dippy" name, feel free to change :)

**Comment by Enriador** [comment]
The very first Diplomacy board had "Tuscany" on it. http://www.dipwiki.com/index.php?title=Image:Original1958Original.gif

The very last Diplomacy board has "Tuscany" on it. http://cf.geekdo-images.com/images/pic1917970.jpg

As standard as it gets! Thanks you all for your hard work for the hobby.

**Comment by tttppp** [comment]
Awesome Diplomacy knowledge! I'll fix and redeploy. It might take a while to see in-app, because the maps are cached. I'll make a note once it's deployed.

**Comment by tttppp** [comment]
Fixed in https://github.com/zond/godip/commit/ee918a2c447aeeb7661df6aa2f1090d7252660d4 and deployed. If you clear your cache then you should see the fix.
