### ISSUE TITLE
Missing toasts?

### ISSUE THREAD

**Issue by tttppp** [zond/android-diplicity#73]
There are meant to be toasts, but I haven't seen them for quite a while. For example I should be told how many units I can build and disband, and when copying the game URL I should see "Game URL copied" or something like that.

Maybe it's my device, or maybe it's the app. Reinstalling and upgrading didn't help.

**Comment by tttppp** [comment]
Ok, presumably it's my device then.

**Comment by zond** [comment]
If you are still in the Hundred game, you should ask someone in the game?
