### ISSUE TITLE
App always opens with Open Games

### ISSUE THREAD

**Issue by tttppp** [zond/android-diplicity#76]
Version 270 starts with Open Games for me, even though I have games already started, and even if I have moves that need making.

I saw there was a change to show this when opening the app, but I thought it was only if the user had no games in progress.

**Comment by zond** [comment]
This is handled by a preference - if you join or start a game (even if you leave it after), the app will go to "My staging" instead.

This is just to make new users see the open games before they start unnecessarily  creating new ones.

**Comment by tttppp** [comment]
Ah - ok. In that case it's working as intended!  At some point we could add some more complex logic, but this seems good for helping new users.
