### ISSUE TITLE
Chat is awkward with long named nations

### ISSUE THREAD

**Issue by tttppp** [zond/android-diplicity#82]
Due to the column based alignment, chat between two nations with long names is very hard to read (it all happens in a thin column on the right). We should consider making messages wrap differently.

**Comment by zond** [comment]
Maybe set a max length and then `android:ellipsize="marquee"` in the TextView?

**Comment by tttppp** [comment]
Fixed in https://github.com/zond/android-diplicity/commit/601b00387e92ca7920fdd989d78832e35a0f317e
