### ISSUE TITLE
Google Drive Storage Exceeded

### ISSUE THREAD

**Issue by tttppp** [zond/android-diplicity#93]
From the latest build:

> panic: googleapi: Error 403: The user's Drive storage quota has been exceeded., storageQuotaExceeded

I think this requires @zond to delete some old build artifacts (deleting all of them might be the simplest option, since we can always build something again if we really need it).

**Comment by zond** [comment]
Ah, when I moved abroad I had to re-subscribe to the Drive storage :)

Done!

**Comment by tttppp** [comment]
Thank you!
